version: "3"

services:

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
      environment:
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
          - "discovery.type=single-node"
          - xpack.security.enabled=false
      ports:
          - "9200:9200"
      volumes:
          - ./elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
      image: docker.elastic.co/kibana/kibana:8.3.3
      ports:
          - "5601:5601"
      depends_on:
          - elasticsearch
